version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trusty
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  adminer:
    image: adminer
    ports: [ "8081:8080" ]

volumes:
  pgdata:
